<?php

declare(strict_types=1);

namespace EduardoKraus\MoodleStringValidate\Rule;

use EduardoKraus\MoodleStringValidate\Check;
use EduardoKraus\MoodleStringValidate\ValidationContext;

final class InstallXmlHeaderRule implements RuleInterface {
    private const XSI_NAMESPACE = "http://www.w3.org/2001/XMLSchema-instance";

    /**
     * Canonical Moodle roots for standard plugin types. Paths intentionally do
     * not contain Moodle 5.x's public/ directory because XMLDB PATH is relative
     * to the Moodle public root, exactly as generated by the XMLDB editor.
     *
     * @var array<string, string>
     */
    private const PLUGIN_TYPE_PATHS = [
        "aiplacement" => "ai/placement",
        "aiprovider" => "ai/provider",
        "antivirus" => "lib/antivirus",
        "availability" => "availability/condition",
        "qtype" => "question/type",
        "mod" => "mod",
        "auth" => "auth",
        "calendartype" => "calendar/type",
        "communication" => "communication/provider",
        "customfield" => "customfield/field",
        "enrol" => "enrol",
        "message" => "message/output",
        "block" => "blocks",
        "media" => "media/player",
        "filter" => "filter",
        "editor" => "lib/editor",
        "format" => "course/format",
        "dataformat" => "dataformat",
        "profilefield" => "user/profile/field",
        "report" => "report",
        "coursereport" => "course/report",
        "gradeexport" => "grade/export",
        "gradeimport" => "grade/import",
        "gradepenalty" => "grade/penalty",
        "gradereport" => "grade/report",
        "gradingform" => "grade/grading/form",
        "mlbackend" => "lib/mlbackend",
        "webservice" => "webservice",
        "repository" => "repository",
        "portfolio" => "portfolio",
        "search" => "search/engine",
        "qbank" => "question/bank",
        "qbehaviour" => "question/behaviour",
        "qformat" => "question/format",
        "plagiarism" => "plagiarism",
        "tool" => "admin/tool",
        "cachestore" => "cache/stores",
        "cachelock" => "cache/locks",
        "fileconverter" => "files/converter",
        "contenttype" => "contentbank/contenttype",
        "theme" => "theme",
        "local" => "local",
        "h5plib" => "h5p/h5plib",
        "paygw" => "payment/gateway",
        "smsgateway" => "sms/gateway",
        "mnetservice" => "mnet/service",

        // Standard subplugin types whose paths are deeper than plugintype/name.
        "assignsubmission" => "mod/assign/submission",
        "assignfeedback" => "mod/assign/feedback",
        "booktool" => "mod/book/tool",
        "datafield" => "mod/data/field",
        "datapreset" => "mod/data/preset",
        "ltisource" => "mod/lti/source",
        "ltiservice" => "mod/lti/service",
        "forumreport" => "mod/forum/report",
        "quiz" => "mod/quiz/report",
        "quizaccess" => "mod/quiz/accessrule",
        "scormreport" => "mod/scorm/report",
        "workshopform" => "mod/workshop/form",
        "workshopallocation" => "mod/workshop/allocation",
        "workshopeval" => "mod/workshop/eval",
        "tiny" => "lib/editor/tiny/plugins",
        "atto" => "lib/editor/atto/plugins",
        "logstore" => "admin/tool/log/store",
        "factor" => "admin/tool/mfa/factor",
    ];

    public function name(): string {
        return "installxml";
    }

    /** @return Check[] */
    public function validate(ValidationContext $context): array {
        $file = $context->pluginroot . "/db/install.xml";
        if (!is_file($file)) {
            return [];
        }

        $source = file_get_contents($file);
        if ($source === false) {
            return [new Check(false, $this->name(), "db/install.xml", 1, "xmldb:header", "Unable to read db/install.xml.")];
        }

        if (preg_match('/<XMLDB\b(?P<attributes>[^>]*)>/is', $source, $match, PREG_OFFSET_CAPTURE) !== 1) {
            return [new Check(
                false,
                $this->name(),
                "db/install.xml",
                1,
                "xmldb:header",
                "db/install.xml must contain an <XMLDB> root element.",
            )];
        }

        $offset = $match[0][1];
        $line = substr_count(substr($source, 0, $offset), "\n") + 1;
        $attributes = $this->parseAttributes($match["attributes"][0]);
        $checks = [];

        $path = trim($attributes["PATH"] ?? "");
        if ($path === "") {
            $checks[] = $this->error($line, "xmldb:path", "<XMLDB> must define a non-empty PATH attribute.");
        } else {
            $checks[] = $this->validatePath($context, $path, $line);
        }

        $version = trim($attributes["VERSION"] ?? "");
        if (!$this->isValidVersion($version)) {
            $checks[] = $this->error(
                $line,
                "xmldb:version",
                "<XMLDB> VERSION must be a valid YYYYMMDD date, for example VERSION=\"20230414\".",
            );
        } else {
            $checks[] = $this->ok($line, "xmldb:version", "XMLDB VERSION '{$version}' is a valid YYYYMMDD date.");
        }

        $comment = trim($attributes["COMMENT"] ?? "");
        if ($comment === "") {
            $checks[] = $this->error($line, "xmldb:comment", "<XMLDB> must define a non-empty COMMENT attribute.");
        } else {
            $checks[] = $this->ok($line, "xmldb:comment", "XMLDB COMMENT is present.");
        }

        $namespace = trim($attributes["xmlns:xsi"] ?? "");
        if ($namespace !== self::XSI_NAMESPACE) {
            $checks[] = $this->error(
                $line,
                "xmldb:xmlns:xsi",
                "<XMLDB> must declare xmlns:xsi=\"" . self::XSI_NAMESPACE . "\".",
            );
        } else {
            $checks[] = $this->ok($line, "xmldb:xmlns:xsi", "XMLDB xsi namespace is correct.");
        }

        if ($path !== "") {
            $expected = $this->schemaLocationForPath($path);
            $actual = trim($attributes["xsi:noNamespaceSchemaLocation"] ?? "");
            if ($actual !== $expected) {
                $checks[] = $this->error(
                    $line,
                    "xmldb:schema",
                    "xsi:noNamespaceSchemaLocation must be '{$expected}' for PATH=\"{$path}\"; got "
                        . ($actual === "" ? "an empty value" : "'{$actual}'") . ".",
                );
            } else {
                $checks[] = $this->ok(
                    $line,
                    "xmldb:schema",
                    "XMLDB schema location '{$actual}' matches PATH depth.",
                );
            }
        }

        return $checks;
    }

    private function validatePath(ValidationContext $context, string $path, int $line): Check {
        if (str_starts_with($path, "/") || str_ends_with($path, "/") || str_contains($path, "\\")
            || str_contains($path, "//") || preg_match('#(?:^|/)\.\.?(/|$)#', $path) === 1) {
            return $this->error(
                $line,
                "xmldb:path",
                "XMLDB PATH '{$path}' must be a normalized Moodle-relative path without leading/trailing slash, backslashes, '.' or '..'.",
            );
        }

        if (!str_ends_with($path, "/db")) {
            return $this->error($line, "xmldb:path", "XMLDB PATH '{$path}' must end in '/db'.");
        }

        $expected = $this->expectedPath($context->component);
        if ($expected !== null && $path !== $expected) {
            return $this->error(
                $line,
                "xmldb:path",
                "XMLDB PATH for component '{$context->component}' must be '{$expected}'; got '{$path}'.",
            );
        }

        return $this->ok(
            $line,
            "xmldb:path",
            $expected === null
                ? "XMLDB PATH '{$path}' is normalized. Plugin type is not in the built-in canonical path map."
                : "XMLDB PATH '{$path}' matches component '{$context->component}'.",
        );
    }

    private function expectedPath(string $component): ?string {
        $separator = strpos($component, "_");
        if ($separator === false || $separator === 0 || $separator === strlen($component) - 1) {
            return null;
        }

        $type = substr($component, 0, $separator);
        $name = substr($component, $separator + 1);
        $root = self::PLUGIN_TYPE_PATHS[$type] ?? null;
        if ($root === null) {
            return null;
        }

        return $root . "/" . $name . "/db";
    }

    private function schemaLocationForPath(string $path): string {
        $segments = array_values(array_filter(explode("/", trim($path, "/")), static fn(string $segment): bool => $segment !== ""));
        return str_repeat("../", count($segments)) . "lib/xmldb/xmldb.xsd";
    }

    /** @return array<string, string> */
    private function parseAttributes(string $source): array {
        $attributes = [];
        if (preg_match_all(
            '/(?<name>[A-Za-z_][A-Za-z0-9_.:-]*)\s*=\s*(?<quote>["\'])(?<value>.*?)\k<quote>/s',
            $source,
            $matches,
            PREG_SET_ORDER,
        )) {
            foreach ($matches as $match) {
                $attributes[$match["name"]] = html_entity_decode(
                    $match["value"],
                    ENT_QUOTES | ENT_XML1,
                    "UTF-8",
                );
            }
        }

        return $attributes;
    }

    private function isValidVersion(string $version): bool {
        if (preg_match('/^(\d{4})(\d{2})(\d{2})$/', $version, $match) !== 1) {
            return false;
        }
        return checkdate((int)$match[2], (int)$match[3], (int)$match[1]);
    }

    private function error(int $line, string $key, string $message): Check {
        return new Check(false, $this->name(), "db/install.xml", max(1, $line), $key, $message);
    }

    private function ok(int $line, string $key, string $message): Check {
        return new Check(true, $this->name(), "db/install.xml", max(1, $line), $key, $message);
    }
}
